content:
  - name: posts
    label: Posts
    type: collection
    format: toml-frontmatter
    path: content/posts
    view:
      fields: [title, draft, date]
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: text, options: {autoresize: true}}
      - { name: draft, label: Draft, default: true, type: boolean }
      - { name: toc, label: TOC, default: true, type: boolean }
      - name: taxonomies
        label: Taxonomies
        type: object
        fields:
          - name: tags
            label: Tags
            type: string
            list: true
            fields:
              - name: name
                label: Tag
                type: string
          - name: categories
            label: Categories
            list: true
            type: string
      - name: extra
        label: Extra
        type: object
        fields:
          - name: keywords
            label: Keywords
            type: string
    filename: "{primary}/index.md"        