content:
  - name: posts
    label: Posts
    type: collection
    format: toml-frontmatter
    path: content/blog
    view:
      fields: [title, draft, date]
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: rich-text, options: {autoresize: true}}
      - { name: draft, label: Draft, default: false, type: boolean }
      - name: taxonomies
        label: Taxonomies
        type: object
        fields:
          - name: tags
            label: Tags
            type: string
            list: true
            fields:
              - name: name
                label: Tag
                type: string
    filename: "{primary}/index.md"        