media:
  input: static/images
  output: images
content:
  - name: posts
    label: Blog posts
    type: collection
    format: toml-frontmatter
    path: content/blog
    view:
      fields: [title, draft, date, slug]
    fields:
      - { name: title, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: date, label: Date (2024-01-01 17:00:00), type: date, options: { time: true, format: YYYY-MM-DD HH:mm:SS } }
      - { name: body, label: Body, type: rich-text, options: {autoresize: true}}
      - { name: draft, label: Draft, default: false, type: boolean }
      - name: taxonomies
        label: Taxonomies
        type: object
        fields:
          - name: tags
            label: Tags
            type: string
            list: true
            fields:
              - name: name
                label: Tag
                type: string
    filename: "{year}-{month}-{day}-{slug}.md"