author = "Phil Wilson"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# whether to generate rss/atom
generate_feeds = true
feed_filenames = ["atom.xml"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "philwilson.org"

taxonomies = [
    { name = "tags", feed = false, paginate_by = 10 },
    { name = "collections", feed = false }
]

[search]
index_format = "elasticlunr_json"

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
# Put all your custom variables here

author_profile_url = "https://0.gravatar.com/avatar/ae6c08ea318da70038c7a967f97e30db2c6a56a51c5a2e1e35897d94c0ebd144"

nav = [
  { name = "About", path = "/about/" },
  { name = "Blog", path = "/blog/" },
  { name = "Stats", path = "/blog/stats" },
  { name = "Blogroll", path = "/blogroll" }
]

latest_text = "Check out my latest post:"

