# The URL the site will be built for
base_url = "http://127.0.0.1:1111"

title = "local site testing"

ignored_content = ["**/200*", "**/201*"]

author = "Phil Wilson"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# whether to generate rss/atom
generate_feed = true
feed_filename = "atom.xml"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "philwilson.org"

taxonomies = [
    { name = "tags", feed = false, paginate_by = 10 }
]

[search]
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

author_profile_url = "https://0.gravatar.com/avatar/ae6c08ea318da70038c7a967f97e30db2c6a56a51c5a2e1e35897d94c0ebd144"

nav = [
  { name = "About", path = "/about/" },
  { name = "Blog", path = "/blog/" },
  { name = "Stats", path = "/blog/stats" },
  { name = "Blogroll", path = "/blogroll" }
]

latest_text = "Check out my latest post:"

accent = "#05a081"
accent_light = "#82d0c0"

footer_page = """
a geek commodity
"""