name: Build and Deploy Zola site

on:
  push:
    branches: [ "production" ]

jobs:
  build_job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@v2
      - run: zola build -u https://zola.philwilson.org
      - with:
            tool: zola@0.17.2
  # deploy_job:
  #   name: deploy
  #   runs-on: ubuntu-latest    
  #   steps:
  #       - name: Checkout
  #       - uses: actions/checkout@v2
  #       - name: deploy file
  #       - uses: wlixcc/SFTP-Deploy-Action@v1.2.4
  #         with:
  #           username: ${{ secrets.SFTP_USERNAME }}
  #           server: ${{ secrets.SFTP_SERVER }}
  #           ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
  #           local_path: './public/*'
  #           remote_path: ${{ secrets.REMOTE_PATH }}
  #           sftpArgs: '-o ConnectTimeout=5'
