name: Build and Deploy Zola site

on:
  push:
    branches: [ "production" ]

jobs:
  copy_services:
    name: copy services to server
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Upload services files to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
            server: ${{ secrets.SFTP_SERVER }}
            protocol: ftps
            username: ${{ secrets.SFTP_USERNAME }}
            password: ${{ secrets.SFTP_PASSWORD }}
            local-dir: ./static/services/
            server-dir: ${{ secrets.REMOTE_PATH }}services/

  build_job:
    name: build
    runs-on: ubuntu-latest
    needs: copy_services
    steps:
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
            tool: zola

      - name: Get latest code
        uses: actions/checkout@v2

      - name: Debug request method
        run: |
          curl -X POST -d '{"text":"https://uk.bookshop.org/p/books/the-centre-ayesha-manazir-siddiqi/7354151?ean=9781529097849"}' https://philwilson.org/services/pip_save_book.php

      - name: Build website
        run: make production

      - name: Run save_microdata_from_urls.py
        run: python3 ./static/services/save_microdata_from_urls.py

      - name: Upload files to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
            server: ${{ secrets.SFTP_SERVER }}
            protocol: ftps
            username: ${{ secrets.SFTP_USERNAME }}
            password: ${{ secrets.SFTP_PASSWORD }}
            local-dir: ./public/
            server-dir: ${{ secrets.REMOTE_PATH }}

  send_webmentions:
    name: send webmentions
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: Install webmention.app
        run: npm install @remy/webmention

      - name: Send webmentions
        run: npx webmention https://philwilson.org/atom.xml --limit 1 --send
