name: Build and Deploy Zola site

on:
  push:
    branches: [ "production" ]

jobs:
  build_job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Zola
      - uses: taiki-e/install-action@v2      
        with:
            tool: zola@0.17.2

      - name: Get latest code
      - uses: actions/checkout@v2            
      - run: zola build -u https://zola.philwilson.org

      - name: Upload files to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
            server: ${{ secrets.SFTP_SERVER }}
            username: ${{ secrets.SFTP_USERNAME }}
            password: ${{ secrets.SFTP_PASSWORD }}
            local-dir: ./public/
            server-dir: ${{ secrets.REMOTE_PATH }}
